FROM alpine:3.3

# USER rust

RUN apk update \
  && apk add --update \
    alpine-sdk \
    bash \
    file \
    curl \
    fuse \
    openssl \
    sudo \
  && rm -rf /var/cache/apk/*

RUN sudo curl -sSf https://static.rust-lang.org/rustup.sh | sudo sh -s -- -y --verbose

# RUN /sbin/ldconfig -v

# Copy package json and install dependencies
COPY . .

RUN which cargo
RUN sudo /usr/local/bin/cargo
